---
name: pr-copy-ci-hato-bot
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  pr-copy-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: npm
          node-version-file: package.json
      - run: npm ci
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "sudden-death"
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          script: |
            const {tsImport} = require('tsx/esm/api')
            const {script} = await tsImport(
              './scripts/pr_copy_ci_hato_bot/pr_copy_ci/dispatch_event.ts',
              process.env.GITHUB_WORKSPACE + '/'
            )
            await script(github, context)
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
