---
name: pr-format
# pull_requestで何かあった時に起動する
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  # PRが来たらformatをかけてみて、差分があればPRを作って、エラーで落ちるjob
  pr-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          # ここでsubmodule持ってくるとdetached headにcommitして死ぬ
          # submodule: 'recursive'
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install xz-utils
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y xz-utils

      - name: Run shellcheck with reviewdog
        uses: reviewdog/action-shellcheck@v1
        with:
          level: error
          reporter: github-pr-review
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
