---
name: pr-test-hato-bot
# pull_requestで何かあった時に起動する
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  # unittestを行う
  # testが落ちたらチェックが落ちる
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"
      - name: Set up uv
        uses: astral-sh/setup-uv@v4.2.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: bash "${GITHUB_WORKSPACE}/scripts/uv_install.sh"
      - name: Test
        run: bash "${GITHUB_WORKSPACE}/scripts/pr_test_hato_bot/pr_test/test.sh"
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
