---
name: pr-test
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  pr-super-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Get uv version
        id: get_uv_version
        run: echo "uv_version=$(sed -e 's/uv==//g' requirements.txt)" >> "$GITHUB_OUTPUT"
      - name: Set up uv
        uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v5.2.2
        with:
          version: ${{steps.get_uv_version.outputs.uv_version}}
          enable-cache: true
      - name: Install uv
        run: bash "${GITHUB_WORKSPACE}/scripts/uv_install.sh"
      - name: Set venv path
        env:
          DEST_PATH: "/home/runner/work/_temp/_github_workflow/.venv"
        run: bash "${GITHUB_WORKSPACE}/scripts/pr_test/pr_super_lint/set_venv_path.sh"
      - name: Set up Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: npm
          node-version-file: package.json
      - name: Install dependencies
        run: bash "${GITHUB_WORKSPACE}/scripts/pr_test/pr_super_lint/npm_ci.sh"
      - name: Lint files
        uses: super-linter/super-linter/slim@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d # v7.2.1
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_SQLFLUFF: false
          VALIDATE_CHECKOV: false # TODO: checkovが依存するopenaiのバージョンがアップデートされたら削除
          VALIDATE_JSCPD: false
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_TYPESCRIPT_STANDARD: false
          LINTER_RULES_PATH: .
          FILTER_REGEX_EXCLUDE: ".*assets/.*.txt"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          WORKON_HOME: ""
          PYTHONPATH: ${{ env.PYTHONPATH }}
  pr-dotenv-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Lint dotenv
        uses: dotenv-linter/action-dotenv-linter@382525b7d91e7b71b52e064b8f1fa5908c4650d2 # v2.24.0
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
